# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/civildot',
                'doc_host': 'https://civildot.github.io',
                'git_url': 'https://github.com/civildot/civildot',
                'lib_path': 'civildot'},
  'syms': {'civildot.core': {'civildot.core.foo': ('core.html#foo', 'civildot/core.py')}}}
